# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_iyN4pkmP5fFEFYBhcKoRrZFpWv-Raq
"""

from flask import Flask, jsonify
import requests

app = Flask(__name__)

@app.route('/start-demo', methods=['GET'])
def start_demo():
    url = "https://tavusapi.com/v2/conversations"

    payload = {
        "replica_id": "r9d30b0e55ac",
        "persona_id": "p6b0e7541d3f",
        "conversation_name": "Science - States of Matter",
        "conversational_context": "...",  # Truncated for readability; include full string from your code
        "custom_greeting": "Hi there! We're going to talk about the states of matter. Can you tell me what the three states of matter are?",
        "properties": {
            "max_call_duration": 180,
            "participant_left_timeout": 5,
            "participant_absent_timeout": 60,
            "enable_recording": True,
            "enable_closed_captions": True,
            "language": "english",
            "recording_s3_bucket_name": "conversation-recordings",
            "recording_s3_bucket_region": "us-east-1",
            "aws_assume_role_arn": ""
        }
    }

    headers = {
        "x-api-key": "f1241dd53a8449fe96ddb7da0a7df444",
        "Content-Type": "application/json"
    }

    response = requests.post(url, json=payload, headers=headers)
    response_json = response.json()
    conversation_url = response_json.get("conversation_url")

    if conversation_url:
        return jsonify({"url": conversation_url})
    else:
        return jsonify({"error": "Failed to start session"}), 500