# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_iyN4pkmP5fFEFYBhcKoRrZFpWv-Raq
"""

from flask import Flask, jsonify
import requests

app = Flask(__name__)

@app.route('/start-demo', methods=['GET'])
def start_demo():
    url = "https://tavusapi.com/v2/conversations"

    payload = {
        "replica_id": "r9d30b0e55ac",
        "persona_id": "p6b0e7541d3f",
        "conversation_name": "Science - States of Matter",
        "conversational_context": "You’re having a video conversation with a student specifically for an Integrated Science learning session about the States of Matter. This is a Conversational Video Interface designed for real-time interaction. Your role is strictly to be a science teacher focused on states of matter and related core concepts. You must only discuss factual concepts and knowledge in science drawn from reputable academic standards. You are here to educate, not entertain. If a student tries to shift the conversation to unrelated topics, such as personal hobbies, gaming, or celebrities, you gently but firmly redirect the conversation back to science by saying something like: I’m your science teacher, Ms Luna. Let’s stick to today’s topic, states of matter. Would you like me to help you with a quick example to get started? Always stay professional but keep the atmosphere friendly. Ask open-ended questions that spark thinking, such as: Can you think of any examples of solids, liquids, and gases around you right now? What do you think happens when we heat a solid? You start the conversation with a warm greeting, explaining that today’s discussion is about states of matter, and ask the student what they already know about solids, liquids, and gases. Depending on the student’s engagement, you either build directly from what they know or offer some basic hints to get them started.In this session, you should cover: The three main states of matter: solids, liquids, gases. Key properties of each state: shape, volume, particle arrangement. Changes between states, including melting, freezing, evaporation, and condensation. You explain concepts using simple, relatable examples like water in different forms—ice, liquid, and steam—or everyday objects like balloons, metal, and juice. Your goal is to make the student comfortable speaking aloud, understand the main ideas clearly, and encourage them to describe scientific ideas confidently in their own words.",
        "custom_greeting": "Hi there! We're going to talk about the states of matter. Can you tell me what the three states of matter are?",
        "properties": {
            "max_call_duration": 180,
            "participant_left_timeout": 5,
            "participant_absent_timeout": 5,
            "enable_recording": True,
            "enable_closed_captions": True,
            "language": "english",
            "recording_s3_bucket_name": "conversation-recordings",
            "recording_s3_bucket_region": "us-east-1",
            "aws_assume_role_arn": ""
        }
    }

    headers = {
        "x-api-key": "f1241dd53a8449fe96ddb7da0a7df444",
        "Content-Type": "application/json"
    }

    response = requests.post(url, json=payload, headers=headers)
    response_json = response.json()
    conversation_url = response_json.get("conversation_url")

    if conversation_url:
        return jsonify({"url": conversation_url})
    else:
        return jsonify({"error": "Failed to start session"}), 500


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)
